### ISSUE TITLE
TTS install

### ISSUE THREAD

**Issue by kloodhu** [roleoroleo/yi-hack-utils#1]
I search everywhere but cant find the article about the tts install to the hacked yi camera. Help me plz, where is it. Thanks!

**Comment by roleoroleo** [comment]
Simply decompress it in /tmp/sd/yi-hack
For example, the binary will be in /tmp/sd/yi-hack/bin

**Comment by kloodhu** [comment]
thank you, working.

**Comment by thboehi** [comment]
Hey!

I tried to run the command:
` nanotts -i "Once upon a midnight dreary" -v en-US --speed 0.8 --pitch 1.8 -w -p`

But I always get the error
` **error: Lang file path not found. Looking in: ./lang, /usr/share/pico/lang`

I correctly added all language files in /tmp/sd/yi-hack/usr/share/pico/lang/
... don't know why it can't work
