### ISSUE TITLE
Nanotts SSH command

### ISSUE THREAD

**Issue by thboehi** [roleoroleo/yi-hack-utils#10]
Hey!

I tried to run the command:
` nanotts -i "Once upon a midnight dreary" -v en-US --speed 0.8 --pitch 1.8 -w -p`

But I always get the error
` **error: Lang file path not found. Looking in: ./lang, /usr/share/pico/lang`

I correctly added all language files in /tmp/sd/yi-hack/usr/share/pico/lang/
... don't know why it can't work. Do you have an idea?

**Comment by roleoroleo** [comment]
Add this option:
`-l /tmp/sd/yi-hack/usr/share/pico/lang`

**Comment by thboehi** [comment]
Thanks for the answer.

The console show now a success message but nothing comes out from the camera... Am I still missing something? And can't find the mentionned file through FTP
```console
/home/yi-hack # nanotts -i "Once upon a midnight dreary" -v en-US --speed 0.8 --pitch 1.8 -w -p -l /tmp/sd/yi-hack/usr/s
hare/pico/lang
Using Lingware directory: /tmp/sd/yi-hack/usr/share/pico/lang
read: 28 bytes from command line
using lang: en-US
speed: 0.80
pitch: 1.80
wrote "nanotts-output-0002.wav" (76076 bytes)
```

**Comment by roleoroleo** [comment]
Check the page http://IP-CAM/?page=speak

And the cgi
https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/master/src/www/httpd/cgi-bin/speak.sh

**Comment by thboehi** [comment]
Thank you !
