### ISSUE TITLE
SFTP client

### ISSUE THREAD

**Issue by Mrivilla** [roleoroleo/yi-hack-utils#2]
Hi @roleoroleo,
Would it be the possibility to have a SSH FTP tool for V2? I will send the videos from several cams to a cloud server, so I would like to secured the transfer.
Another possibility is run a script with scp and some prework with certificates, leveraging the gdrive script.

Thanks.
Marcos.

**Comment by roleoroleo** [comment]
Do you want to try?
I didn't test it.
[openssh.tar.gz](https://github.com/roleoroleo/yi-hack-utils/files/7829833/openssh.tar.gz)

**Comment by Mrivilla** [comment]
Hello @roleoroleo,
all seems to be working. 
Of course the libopenssh need to be extracted as well and setup the environment, but I connected using ssh and sftp clien runs.
Thanks.
Marcos.
![image](https://user-images.githubusercontent.com/13434459/149535468-b10f02ee-6a55-4dd0-be41-8958ecbae8d5.png)

**Comment by roleoroleo** [comment]
If you are on Allwinner platform:
you should copy all binaries in /tmp/sd/yi-hack/bin nd source the env
```
. /tmp/sd/yi-hack/script/env
```
