### ISSUE TITLE
Hi, diference from Allwinner-v2 and Allwinner

### ISSUE THREAD

**Issue by ricardojlrufino** [roleoroleo/yi-hack-utils#4]
I just bought a camera and I'm going to implement the QRCODE reader in it too.

I just found it strange that the utils are also different....

What is the difference between the two for the binaries not to work?

**Comment by roleoroleo** [comment]
Binaries are compatibles.
The only difference is the partitions schema.
Allwinner works with a jffs2 (r/w) home partition.
Allwinner-v2 works with a squashfs (read only) home partition.
So v2 requires an sd card to run the hack.

**Comment by ricardojlrufino** [comment]
OK, thanks man !!

**Comment by ricardojlrufino** [comment]
I'm hacking another camera.
In it I was able to access the image sensor directly too, and the good thing is that it has a lot of GPIO to play with.

https://ricardojlrufino.wordpress.com/2022/02/14/hack-ipcam-anyka-teardown-and-root-access/
