### ISSUE TITLE
Can we get an rsync package for Allwinner?

### ISSUE THREAD

**Issue by othyro** [roleoroleo/yi-hack-utils#7]
I have the nanotts package installed and it works great via your Home Assistant integration. Could we please get an rsync package too? That would be nice to have for syncing files between the camera and various devices.

**Comment by roleoroleo** [comment]
rsync added.
Please, let me know if it works.

**Comment by othyro** [comment]
Sick! Thanks, m8. However, it's missing libcrypto:

% rsync -a root@camera1:/tmp/sd/record . --delete
Error loading shared library libcrypto.so.1.1: No such file or directory (needed by /tmp/sd/yi-hack/bin/rsync)
Error relocating /tmp/sd/yi-hack/bin/rsync: EVP_DigestInit_ex: symbol not found
Error relocating /tmp/sd/yi-hack/bin/rsync: EVP_get_digestbyname: symbol not found
Error relocating /tmp/sd/yi-hack/bin/rsync: EVP_DigestUpdate: symbol not found
Error relocating /tmp/sd/yi-hack/bin/rsync: EVP_DigestFinal_ex: symbol not found
Error relocating /tmp/sd/yi-hack/bin/rsync: EVP_MD_CTX_new: symbol not found
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [Receiver=3.2.7]

root@camera1:/tmp/sd/yi-hack/bin# ldd rsync 
	/lib/ld-musl-armhf.so.1 (0xb6f63000)
Error loading shared library libcrypto.so.1.1: No such file or directory (needed by rsync)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb6f49000)
	libc.so => /lib/ld-musl-armhf.so.1 (0xb6f63000)
Error relocating rsync: EVP_DigestInit_ex: symbol not found
Error relocating rsync: EVP_get_digestbyname: symbol not found
Error relocating rsync: EVP_DigestUpdate: symbol not found
Error relocating rsync: EVP_DigestFinal_ex: symbol not found
Error relocating rsync: EVP_MD_CTX_new: symbol not found

**Comment by roleoroleo** [comment]
Download libopenssl from the same repo and copy the libs in /tmp/sd/yi-hack/lib
Pay attention: fat32 card doesn't support symbolic links. Copy the same lib files with 3 different names.
*.so
*.so.1
*.so.1.1
