### ISSUE TITLE
Home Assistant Rest Command Not Working

### ISSUE THREAD

**Issue by johnwilliever** [roleoroleo/yi-hack-utils#8]
Hi, I installed the nanotts on my cam and using the speak page, it works properly. But when I use the rest command in home assistant, it is not working and got a status code 401.

Please see the attached pic for reference.
![Screenshot_20230725-235109](https://github.com/roleoroleo/yi-hack-utils/assets/92567532/c8e4acc9-a4d8-4997-8a19-34da9bc36fb1)

**Comment by roleoroleo** [comment]
Did you set http authentication in the cam?
And, did you set http authentication after adding the cam to ha?

**Comment by johnwilliever** [comment]
Yes, first I configured the http authentication in the cam and after, I added the cam into the HA. But, I reset the cam and reapplied the hack and added the nanotts.

Does it require to remove the cam from HA and add it again?

**Comment by johnwilliever** [comment]
Update: I removed the cam from HA and added it again. Same error, I got status code 401.

**Comment by johnwilliever** [comment]
Update: It's working now. I added rest command username and password variables in the configuration.yaml.

**Comment by roleoroleo** [comment]
Now I understand.
You are not using the service yi_hack.speak.
You are using the rest api directly.
In this case you need to add user and password.

You could try to use the service.

**Comment by johnwilliever** [comment]
I see. I didn't know there's such a service under yi hack integration. I just follow your rest command example code posted on allwinner page. Anyway, thank you for this great camera hack.
